# generated by datamodel-codegen:
#   filename:  ctgov-openapi.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WebLink(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: str
    url: str


class SearchPart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    is_enum: Annotated[bool, Field(alias="isEnum")]
    is_synonyms: Annotated[bool, Field(alias="isSynonyms")]
    pieces: list[str]
    type: str
    weight: float


class EnumItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    exceptions: dict[str, Any] | None = None
    legacy_value: Annotated[str, Field(alias="legacyValue")]
    value: str


class StudySize(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    size_bytes: Annotated[int, Field(alias="sizeBytes")]


class DistItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    size_range: Annotated[str, Field(alias="sizeRange")]
    studies_count: Annotated[int, Field(alias="studiesCount")]


class ListSize(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    size: int
    studies_count: Annotated[int, Field(alias="studiesCount")]


class ValueCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    studies_count: Annotated[int, Field(alias="studiesCount")]
    value: str


class FieldStatsType(StrEnum):
    enum = "ENUM"
    string = "STRING"
    date = "DATE"
    integer = "INTEGER"
    number = "NUMBER"
    boolean = "BOOLEAN"


class LongestString(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    length: int
    nct_id: Annotated[str, Field(alias="nctId")]
    value: str


class DateStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    formats: list[str]
    max: str | None = None
    min: str | None = None
    missing_studies_count: Annotated[int, Field(alias="missingStudiesCount")]
    piece: str
    type: FieldStatsType


class IntegerStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    avg: float | None = None
    field: str
    max: int | None = None
    min: int | None = None
    missing_studies_count: Annotated[int, Field(alias="missingStudiesCount")]
    piece: str
    type: FieldStatsType


class NumberStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    avg: float | None = None
    field: str
    max: float | None = None
    min: float | None = None
    missing_studies_count: Annotated[int, Field(alias="missingStudiesCount")]
    piece: str
    type: FieldStatsType


class BooleanStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    false_count: Annotated[int, Field(alias="falseCount")]
    field: str
    missing_studies_count: Annotated[int, Field(alias="missingStudiesCount")]
    piece: str
    true_count: Annotated[int, Field(alias="trueCount")]
    type: FieldStatsType


class Version(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api_version: Annotated[str, Field(alias="apiVersion")]
    data_timestamp: Annotated[str | None, Field(alias="dataTimestamp")] = None


class OversightModule(BaseModel):
    oversight_has_dmc: Annotated[bool | None, Field(alias="oversightHasDmc")] = None
    is_fda_regulated_drug: Annotated[bool | None, Field(alias="isFdaRegulatedDrug")] = None
    is_fda_regulated_device: Annotated[bool | None, Field(alias="isFdaRegulatedDevice")] = None
    is_unapproved_device: Annotated[bool | None, Field(alias="isUnapprovedDevice")] = None
    is_ppsd: Annotated[bool | None, Field(alias="isPpsd")] = None
    is_us_export: Annotated[bool | None, Field(alias="isUsExport")] = None
    fdaaa801_violation: Annotated[bool | None, Field(alias="fdaaa801Violation")] = None


class DescriptionModule(BaseModel):
    brief_summary: Annotated[str | None, Field(alias="briefSummary")] = None
    detailed_description: Annotated[str | None, Field(alias="detailedDescription")] = None


class ConditionsModule(BaseModel):
    conditions: list[str] | None = None
    keywords: list[str] | None = None


class SeeAlsoLink(BaseModel):
    label: str | None = None
    url: str | None = None


class ExpandedAccessTypes(BaseModel):
    individual: bool | None = None
    intermediate: bool | None = None
    treatment: bool | None = None


class AvailIpd(BaseModel):
    id: str | None = None
    type: str | None = None
    url: str | None = None
    comment: str | None = None


class LimitationsAndCaveats(BaseModel):
    description: str | None = None


class SubmissionInfo(BaseModel):
    release_date: Annotated[date_aliased | None, Field(alias="releaseDate")] = None
    unrelease_date: Annotated[date_aliased | None, Field(alias="unreleaseDate")] = None
    unrelease_date_unknown: Annotated[bool | None, Field(alias="unreleaseDateUnknown")] = None
    reset_date: Annotated[date_aliased | None, Field(alias="resetDate")] = None
    mcp_release_n: Annotated[int | None, Field(alias="mcpReleaseN")] = None


class PointOfContact(BaseModel):
    title: str | None = None
    organization: str | None = None
    email: str | None = None
    phone: str | None = None
    phone_ext: Annotated[str | None, Field(alias="phoneExt")] = None


class Outcome(BaseModel):
    measure: str | None = None
    description: str | None = None
    time_frame: Annotated[str | None, Field(alias="timeFrame")] = None


class EventGroup(BaseModel):
    id: str | None = None
    title: str | None = None
    description: str | None = None
    deaths_num_affected: Annotated[int | None, Field(alias="deathsNumAffected")] = None
    deaths_num_at_risk: Annotated[int | None, Field(alias="deathsNumAtRisk")] = None
    serious_num_affected: Annotated[int | None, Field(alias="seriousNumAffected")] = None
    serious_num_at_risk: Annotated[int | None, Field(alias="seriousNumAtRisk")] = None
    other_num_affected: Annotated[int | None, Field(alias="otherNumAffected")] = None
    other_num_at_risk: Annotated[int | None, Field(alias="otherNumAtRisk")] = None


class Mesh(BaseModel):
    id: str | None = None
    term: str | None = None


class FlowGroup(BaseModel):
    id: str | None = None
    title: str | None = None
    description: str | None = None


class Retraction(BaseModel):
    pmid: str | None = None
    source: str | None = None


class MeasureGroup(BaseModel):
    id: str | None = None
    title: str | None = None
    description: str | None = None


class BrowseBranch(BaseModel):
    abbrev: str | None = None
    name: str | None = None


class DenomCount(BaseModel):
    group_id: Annotated[str | None, Field(alias="groupId")] = None
    value: str | None = None


class EventStats(BaseModel):
    group_id: Annotated[str | None, Field(alias="groupId")] = None
    num_events: Annotated[int | None, Field(alias="numEvents")] = None
    num_affected: Annotated[int | None, Field(alias="numAffected")] = None
    num_at_risk: Annotated[int | None, Field(alias="numAtRisk")] = None


class FlowStats(BaseModel):
    group_id: Annotated[str | None, Field(alias="groupId")] = None
    comment: str | None = None
    num_subjects: Annotated[str | None, Field(alias="numSubjects")] = None
    num_units: Annotated[str | None, Field(alias="numUnits")] = None


class Measurement(BaseModel):
    group_id: Annotated[str | None, Field(alias="groupId")] = None
    value: str | None = None
    spread: str | None = None
    lower_limit: Annotated[str | None, Field(alias="lowerLimit")] = None
    upper_limit: Annotated[str | None, Field(alias="upperLimit")] = None
    comment: str | None = None


class Status(StrEnum):
    active_not_recruiting = "ACTIVE_NOT_RECRUITING"
    completed = "COMPLETED"
    enrolling_by_invitation = "ENROLLING_BY_INVITATION"
    not_yet_recruiting = "NOT_YET_RECRUITING"
    recruiting = "RECRUITING"
    suspended = "SUSPENDED"
    terminated = "TERMINATED"
    withdrawn = "WITHDRAWN"
    available = "AVAILABLE"
    no_longer_available = "NO_LONGER_AVAILABLE"
    temporarily_not_available = "TEMPORARILY_NOT_AVAILABLE"
    approved_for_marketing = "APPROVED_FOR_MARKETING"
    withheld = "WITHHELD"
    unknown = "UNKNOWN"


class StudyType(StrEnum):
    expanded_access = "EXPANDED_ACCESS"
    interventional = "INTERVENTIONAL"
    observational = "OBSERVATIONAL"


class Phase(StrEnum):
    na = "NA"
    early_phase1 = "EARLY_PHASE1"
    phase1 = "PHASE1"
    phase2 = "PHASE2"
    phase3 = "PHASE3"
    phase4 = "PHASE4"


class Sex(StrEnum):
    female = "FEMALE"
    male = "MALE"
    all = "ALL"


class StandardAge(StrEnum):
    child = "CHILD"
    adult = "ADULT"
    older_adult = "OLDER_ADULT"


class SamplingMethod(StrEnum):
    probability_sample = "PROBABILITY_SAMPLE"
    non_probability_sample = "NON_PROBABILITY_SAMPLE"


class IpdSharing(StrEnum):
    yes = "YES"
    no = "NO"
    undecided = "UNDECIDED"


class IpdSharingInfoType(StrEnum):
    study_protocol = "STUDY_PROTOCOL"
    sap = "SAP"
    icf = "ICF"
    csr = "CSR"
    analytic_code = "ANALYTIC_CODE"


class OrgStudyIdType(StrEnum):
    nih = "NIH"
    fda = "FDA"
    va = "VA"
    cdc = "CDC"
    ahrq = "AHRQ"
    samhsa = "SAMHSA"


class SecondaryIdType(StrEnum):
    nih = "NIH"
    fda = "FDA"
    va = "VA"
    cdc = "CDC"
    ahrq = "AHRQ"
    samhsa = "SAMHSA"
    other_grant = "OTHER_GRANT"
    eudract_number = "EUDRACT_NUMBER"
    ctis = "CTIS"
    registry = "REGISTRY"
    other = "OTHER"


class AgencyClass(StrEnum):
    nih = "NIH"
    fed = "FED"
    other_gov = "OTHER_GOV"
    indiv = "INDIV"
    industry = "INDUSTRY"
    network = "NETWORK"
    ambig = "AMBIG"
    other = "OTHER"
    unknown = "UNKNOWN"


class ExpandedAccessStatus(StrEnum):
    available = "AVAILABLE"
    no_longer_available = "NO_LONGER_AVAILABLE"
    temporarily_not_available = "TEMPORARILY_NOT_AVAILABLE"
    approved_for_marketing = "APPROVED_FOR_MARKETING"


class DateType(StrEnum):
    actual = "ACTUAL"
    estimated = "ESTIMATED"


class ResponsiblePartyType(StrEnum):
    sponsor = "SPONSOR"
    principal_investigator = "PRINCIPAL_INVESTIGATOR"
    sponsor_investigator = "SPONSOR_INVESTIGATOR"


class DesignAllocation(StrEnum):
    randomized = "RANDOMIZED"
    non_randomized = "NON_RANDOMIZED"
    na = "NA"


class InterventionalAssignment(StrEnum):
    single_group = "SINGLE_GROUP"
    parallel = "PARALLEL"
    crossover = "CROSSOVER"
    factorial = "FACTORIAL"
    sequential = "SEQUENTIAL"


class PrimaryPurpose(StrEnum):
    treatment = "TREATMENT"
    prevention = "PREVENTION"
    diagnostic = "DIAGNOSTIC"
    ect = "ECT"
    supportive_care = "SUPPORTIVE_CARE"
    screening = "SCREENING"
    health_services_research = "HEALTH_SERVICES_RESEARCH"
    basic_science = "BASIC_SCIENCE"
    device_feasibility = "DEVICE_FEASIBILITY"
    other = "OTHER"


class ObservationalModel(StrEnum):
    cohort = "COHORT"
    case_control = "CASE_CONTROL"
    case_only = "CASE_ONLY"
    case_crossover = "CASE_CROSSOVER"
    ecologic_or_community = "ECOLOGIC_OR_COMMUNITY"
    family_based = "FAMILY_BASED"
    defined_population = "DEFINED_POPULATION"
    natural_history = "NATURAL_HISTORY"
    other = "OTHER"


class DesignTimePerspective(StrEnum):
    retrospective = "RETROSPECTIVE"
    prospective = "PROSPECTIVE"
    cross_sectional = "CROSS_SECTIONAL"
    other = "OTHER"


class BioSpecRetention(StrEnum):
    none_retained = "NONE_RETAINED"
    samples_with_dna = "SAMPLES_WITH_DNA"
    samples_without_dna = "SAMPLES_WITHOUT_DNA"


class EnrollmentType(StrEnum):
    actual = "ACTUAL"
    estimated = "ESTIMATED"


class ArmGroupType(StrEnum):
    experimental = "EXPERIMENTAL"
    active_comparator = "ACTIVE_COMPARATOR"
    placebo_comparator = "PLACEBO_COMPARATOR"
    sham_comparator = "SHAM_COMPARATOR"
    no_intervention = "NO_INTERVENTION"
    other = "OTHER"


class InterventionType(StrEnum):
    behavioral = "BEHAVIORAL"
    biological = "BIOLOGICAL"
    combination_product = "COMBINATION_PRODUCT"
    device = "DEVICE"
    diagnostic_test = "DIAGNOSTIC_TEST"
    dietary_supplement = "DIETARY_SUPPLEMENT"
    drug = "DRUG"
    genetic = "GENETIC"
    procedure = "PROCEDURE"
    radiation = "RADIATION"
    other = "OTHER"


class ContactRole(StrEnum):
    study_chair = "STUDY_CHAIR"
    study_director = "STUDY_DIRECTOR"
    principal_investigator = "PRINCIPAL_INVESTIGATOR"
    sub_investigator = "SUB_INVESTIGATOR"
    contact = "CONTACT"


class OfficialRole(StrEnum):
    study_chair = "STUDY_CHAIR"
    study_director = "STUDY_DIRECTOR"
    principal_investigator = "PRINCIPAL_INVESTIGATOR"
    sub_investigator = "SUB_INVESTIGATOR"


class RecruitmentStatus(StrEnum):
    active_not_recruiting = "ACTIVE_NOT_RECRUITING"
    completed = "COMPLETED"
    enrolling_by_invitation = "ENROLLING_BY_INVITATION"
    not_yet_recruiting = "NOT_YET_RECRUITING"
    recruiting = "RECRUITING"
    suspended = "SUSPENDED"
    terminated = "TERMINATED"
    withdrawn = "WITHDRAWN"
    available = "AVAILABLE"


class ReferenceType(StrEnum):
    background = "BACKGROUND"
    result = "RESULT"
    derived = "DERIVED"


class MeasureParam(StrEnum):
    geometric_mean = "GEOMETRIC_MEAN"
    geometric_least_squares_mean = "GEOMETRIC_LEAST_SQUARES_MEAN"
    least_squares_mean = "LEAST_SQUARES_MEAN"
    log_mean = "LOG_MEAN"
    mean = "MEAN"
    median = "MEDIAN"
    number = "NUMBER"
    count_of_participants = "COUNT_OF_PARTICIPANTS"
    count_of_units = "COUNT_OF_UNITS"


class MeasureDispersionType(StrEnum):
    na = "NA"
    standard_deviation = "STANDARD_DEVIATION"
    standard_error = "STANDARD_ERROR"
    inter_quartile_range = "INTER_QUARTILE_RANGE"
    full_range = "FULL_RANGE"
    confidence_80 = "CONFIDENCE_80"
    confidence_90 = "CONFIDENCE_90"
    confidence_95 = "CONFIDENCE_95"
    confidence_975 = "CONFIDENCE_975"
    confidence_99 = "CONFIDENCE_99"
    confidence_other = "CONFIDENCE_OTHER"
    geometric_coefficient = "GEOMETRIC_COEFFICIENT"


class OutcomeMeasureType(StrEnum):
    primary = "PRIMARY"
    secondary = "SECONDARY"
    other_pre_specified = "OTHER_PRE_SPECIFIED"
    post_hoc = "POST_HOC"


class ReportingStatus(StrEnum):
    not_posted = "NOT_POSTED"
    posted = "POSTED"


class EventAssessment(StrEnum):
    non_systematic_assessment = "NON_SYSTEMATIC_ASSESSMENT"
    systematic_assessment = "SYSTEMATIC_ASSESSMENT"


class AgreementRestrictionType(StrEnum):
    lte60 = "LTE60"
    gt60 = "GT60"
    other = "OTHER"


class BrowseLeafRelevance(StrEnum):
    low = "LOW"
    high = "HIGH"


class DesignMasking(StrEnum):
    none = "NONE"
    single = "SINGLE"
    double = "DOUBLE"
    triple = "TRIPLE"
    quadruple = "QUADRUPLE"


class WhoMasked(StrEnum):
    participant = "PARTICIPANT"
    care_provider = "CARE_PROVIDER"
    investigator = "INVESTIGATOR"
    outcomes_assessor = "OUTCOMES_ASSESSOR"


class AnalysisDispersionType(StrEnum):
    standard_deviation = "STANDARD_DEVIATION"
    standard_error_of_mean = "STANDARD_ERROR_OF_MEAN"


class ConfidenceIntervalNumSides(StrEnum):
    one_sided = "ONE_SIDED"
    two_sided = "TWO_SIDED"


class NonInferiorityType(StrEnum):
    superiority = "SUPERIORITY"
    non_inferiority = "NON_INFERIORITY"
    equivalence = "EQUIVALENCE"
    other = "OTHER"
    non_inferiority_or_equivalence = "NON_INFERIORITY_OR_EQUIVALENCE"
    superiority_or_other = "SUPERIORITY_OR_OTHER"
    non_inferiority_or_equivalence_legacy = "NON_INFERIORITY_OR_EQUIVALENCE_LEGACY"
    superiority_or_other_legacy = "SUPERIORITY_OR_OTHER_LEGACY"


class UnpostedEventType(StrEnum):
    reset = "RESET"
    release = "RELEASE"
    unrelease = "UNRELEASE"


class ViolationEventType(StrEnum):
    violation_identified = "VIOLATION_IDENTIFIED"
    correction_confirmed = "CORRECTION_CONFIRMED"
    penalty_imposed = "PENALTY_IMPOSED"
    issues_in_letter_addressed_confirmed = "ISSUES_IN_LETTER_ADDRESSED_CONFIRMED"


class GeoPoint(BaseModel):
    lat: float
    lon: float


class StudiesCsv(RootModel[str]):
    root: Annotated[str, Field(description="Study objects in csv file")]


class StudiesZip(RootModel[str]):
    root: Annotated[str, Field(description="Study objects as files in zip archive")]


class StudyFhir(BaseModel):
    """
    Study in FHIR JSON format
    """


class Csv(RootModel[str]):
    root: Annotated[str, Field(description="CSV file")]


class Nct(RootModel[str]):
    root: Annotated[str, Field(description="NCT number", max_length=11, min_length=11)]


class PartialDate(RootModel[str]):
    root: Annotated[str, Field(description="Date in `yyyy`, `yyyy-MM`, or `yyyy-MM-dd` format")]


class DateTimeMinutes(RootModel[str]):
    root: Annotated[str, Field(description="Date and time in `yyyy-MM-dd'T'HH:mm` format")]


class GeoName(RootModel[str]):
    root: Annotated[str, Field(description="State/province or city name")]


class ErrorMessage(RootModel[str]):
    root: Annotated[str, Field(description="A text message describing an error")]


class FieldNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alt_piece_names: Annotated[list[str] | None, Field(alias="altPieceNames")] = None
    children: list[FieldNode] | None = None
    ded_link: Annotated[WebLink | None, Field(alias="dedLink")] = None
    description: str | None = None
    historic_only: Annotated[bool | None, Field(alias="historicOnly")] = None
    indexed_only: Annotated[bool | None, Field(alias="indexedOnly")] = None
    is_enum: Annotated[bool | None, Field(alias="isEnum")] = None
    max_chars: Annotated[int | None, Field(alias="maxChars")] = None
    name: str
    nested: bool | None = None
    piece: str
    rules: str | None = None
    source_type: Annotated[str, Field(alias="sourceType")]
    synonyms: bool | None = None
    title: str | None = None
    type: str


class FieldNodeList(RootModel[list[FieldNode]]):
    root: list[FieldNode]


class SearchArea(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    param: str | None = None
    parts: list[SearchPart]
    ui_label: Annotated[str | None, Field(alias="uiLabel")] = None


class EnumInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pieces: list[str]
    type: str
    values: list[EnumItem]


class EnumInfoList(RootModel[list[EnumInfo]]):
    root: list[EnumInfo]


class GzipStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    average_size_bytes: Annotated[int, Field(alias="averageSizeBytes")]
    largest_studies: Annotated[list[StudySize], Field(alias="largestStudies")]
    percentiles: dict[str, Any]
    ranges: list[DistItem]
    total_studies: Annotated[int, Field(alias="totalStudies")]


class ListSizes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    max_size: Annotated[int | None, Field(alias="maxSize")] = None
    min_size: Annotated[int | None, Field(alias="minSize")] = None
    piece: str
    top_sizes: Annotated[list[ListSize] | None, Field(alias="topSizes")] = None
    unique_sizes_count: Annotated[int, Field(alias="uniqueSizesCount")]


class ListSizesList(RootModel[list[ListSizes]]):
    root: list[ListSizes]


class EnumStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    missing_studies_count: Annotated[int, Field(alias="missingStudiesCount")]
    piece: str
    top_values: Annotated[list[ValueCount] | None, Field(alias="topValues")] = None
    type: FieldStatsType
    unique_values_count: Annotated[int, Field(alias="uniqueValuesCount")]


class StringStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    longest: LongestString | None = None
    missing_studies_count: Annotated[int, Field(alias="missingStudiesCount")]
    piece: str
    top_values: Annotated[list[ValueCount] | None, Field(alias="topValues")] = None
    type: FieldStatsType
    unique_values_count: Annotated[int, Field(alias="uniqueValuesCount")]


class OutcomesModule(BaseModel):
    primary_outcomes: Annotated[list[Outcome] | None, Field(alias="primaryOutcomes")] = None
    secondary_outcomes: Annotated[list[Outcome] | None, Field(alias="secondaryOutcomes")] = None
    other_outcomes: Annotated[list[Outcome] | None, Field(alias="otherOutcomes")] = None


class EligibilityModule(BaseModel):
    eligibility_criteria: Annotated[str | None, Field(alias="eligibilityCriteria")] = None
    healthy_volunteers: Annotated[bool | None, Field(alias="healthyVolunteers")] = None
    sex: Sex | None = None
    gender_based: Annotated[bool | None, Field(alias="genderBased")] = None
    gender_description: Annotated[str | None, Field(alias="genderDescription")] = None
    minimum_age: Annotated[
        str | None,
        Field(
            alias="minimumAge",
            pattern="^\\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$",
        ),
    ] = None
    maximum_age: Annotated[
        str | None,
        Field(
            alias="maximumAge",
            pattern="^\\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$",
        ),
    ] = None
    std_ages: Annotated[list[StandardAge] | None, Field(alias="stdAges")] = None
    study_population: Annotated[str | None, Field(alias="studyPopulation")] = None
    sampling_method: Annotated[SamplingMethod | None, Field(alias="samplingMethod")] = None


class EnrollmentInfo(BaseModel):
    count: int | None = None
    type: EnrollmentType | None = None


class BioSpec(BaseModel):
    retention: BioSpecRetention | None = None
    description: str | None = None


class Intervention(BaseModel):
    type: InterventionType | None = None
    name: str | None = None
    description: str | None = None
    arm_group_labels: Annotated[list[str] | None, Field(alias="armGroupLabels")] = None
    other_names: Annotated[list[str] | None, Field(alias="otherNames")] = None


class SecondaryIdInfo(BaseModel):
    id: str | None = None
    type: SecondaryIdType | None = None
    domain: str | None = None
    link: str | None = None


class DateStruct(BaseModel):
    date: date_aliased | None = None
    type: DateType | None = None


class ExpandedAccessInfo(BaseModel):
    has_expanded_access: Annotated[bool | None, Field(alias="hasExpandedAccess")] = None
    nct_id: Annotated[Nct | None, Field(alias="nctId")] = None
    status_for_nct_id: Annotated[ExpandedAccessStatus | None, Field(alias="statusForNctId")] = None


class ViolationEvent(BaseModel):
    type: ViolationEventType | None = None
    description: str | None = None
    creation_date: Annotated[date_aliased | None, Field(alias="creationDate")] = None
    issued_date: Annotated[date_aliased | None, Field(alias="issuedDate")] = None
    release_date: Annotated[date_aliased | None, Field(alias="releaseDate")] = None
    posted_date: Annotated[date_aliased | None, Field(alias="postedDate")] = None


class ArmGroup(BaseModel):
    label: str | None = None
    type: ArmGroupType | None = None
    description: str | None = None
    intervention_names: Annotated[list[str] | None, Field(alias="interventionNames")] = None


class Organization(BaseModel):
    full_name: Annotated[str | None, Field(alias="fullName")] = None
    class_: Annotated[AgencyClass | None, Field(alias="class")] = None


class IpdSharingStatementModule(BaseModel):
    ipd_sharing: Annotated[IpdSharing | None, Field(alias="ipdSharing")] = None
    description: str | None = None
    info_types: Annotated[list[IpdSharingInfoType] | None, Field(alias="infoTypes")] = None
    time_frame: Annotated[str | None, Field(alias="timeFrame")] = None
    access_criteria: Annotated[str | None, Field(alias="accessCriteria")] = None
    url: str | None = None


class OrgStudyIdInfo(BaseModel):
    id: str | None = None
    type: OrgStudyIdType | None = None
    link: str | None = None


class ResponsibleParty(BaseModel):
    type: ResponsiblePartyType | None = None
    investigator_full_name: Annotated[str | None, Field(alias="investigatorFullName")] = None
    investigator_title: Annotated[str | None, Field(alias="investigatorTitle")] = None
    investigator_affiliation: Annotated[str | None, Field(alias="investigatorAffiliation")] = None
    old_name_title: Annotated[str | None, Field(alias="oldNameTitle")] = None
    old_organization: Annotated[str | None, Field(alias="oldOrganization")] = None


class CertainAgreement(BaseModel):
    pi_sponsor_employee: Annotated[bool | None, Field(alias="piSponsorEmployee")] = None
    restriction_type: Annotated[AgreementRestrictionType | None, Field(alias="restrictionType")] = (
        None
    )
    restrictive_agreement: Annotated[bool | None, Field(alias="restrictiveAgreement")] = None
    other_details: Annotated[str | None, Field(alias="otherDetails")] = None


class UnpostedEvent(BaseModel):
    type: UnpostedEventType | None = None
    date: date_aliased | None = None
    date_unknown: Annotated[bool | None, Field(alias="dateUnknown")] = None


class Contact(BaseModel):
    name: str | None = None
    role: ContactRole | None = None
    phone: str | None = None
    phone_ext: Annotated[str | None, Field(alias="phoneExt")] = None
    email: str | None = None


class PartialDateStruct(BaseModel):
    date: PartialDate | None = None
    type: DateType | None = None


class Reference(BaseModel):
    pmid: str | None = None
    type: ReferenceType | None = None
    citation: str | None = None
    retractions: list[Retraction] | None = None


class Location(BaseModel):
    facility: str | None = None
    status: RecruitmentStatus | None = None
    city: GeoName | None = None
    state: GeoName | None = None
    zip: str | None = None
    country: str | None = None
    contacts: list[Contact] | None = None
    geo_point: Annotated[GeoPoint | None, Field(alias="geoPoint")] = None


class Sponsor(BaseModel):
    name: str | None = None
    class_: Annotated[AgencyClass | None, Field(alias="class")] = None


class Official(BaseModel):
    name: str | None = None
    affiliation: str | None = None
    role: OfficialRole | None = None


class BrowseLeaf(BaseModel):
    id: str | None = None
    name: str | None = None
    as_found: Annotated[str | None, Field(alias="asFound")] = None
    relevance: BrowseLeafRelevance | None = None


class MaskingBlock(BaseModel):
    masking: DesignMasking | None = None
    masking_description: Annotated[str | None, Field(alias="maskingDescription")] = None
    who_masked: Annotated[list[WhoMasked] | None, Field(alias="whoMasked")] = None


class MeasureAnalysis(BaseModel):
    param_type: Annotated[str | None, Field(alias="paramType")] = None
    param_value: Annotated[str | None, Field(alias="paramValue")] = None
    dispersion_type: Annotated[AnalysisDispersionType | None, Field(alias="dispersionType")] = None
    dispersion_value: Annotated[str | None, Field(alias="dispersionValue")] = None
    statistical_method: Annotated[str | None, Field(alias="statisticalMethod")] = None
    statistical_comment: Annotated[str | None, Field(alias="statisticalComment")] = None
    p_value: Annotated[str | None, Field(alias="pValue")] = None
    p_value_comment: Annotated[str | None, Field(alias="pValueComment")] = None
    ci_num_sides: Annotated[ConfidenceIntervalNumSides | None, Field(alias="ciNumSides")] = None
    ci_pct_value: Annotated[str | None, Field(alias="ciPctValue")] = None
    ci_lower_limit: Annotated[str | None, Field(alias="ciLowerLimit")] = None
    ci_upper_limit: Annotated[str | None, Field(alias="ciUpperLimit")] = None
    ci_lower_limit_comment: Annotated[str | None, Field(alias="ciLowerLimitComment")] = None
    ci_upper_limit_comment: Annotated[str | None, Field(alias="ciUpperLimitComment")] = None
    estimate_comment: Annotated[str | None, Field(alias="estimateComment")] = None
    tested_non_inferiority: Annotated[bool | None, Field(alias="testedNonInferiority")] = None
    non_inferiority_type: Annotated[
        NonInferiorityType | None, Field(alias="nonInferiorityType")
    ] = None
    non_inferiority_comment: Annotated[str | None, Field(alias="nonInferiorityComment")] = None
    other_analysis_description: Annotated[str | None, Field(alias="otherAnalysisDescription")] = (
        None
    )
    group_description: Annotated[str | None, Field(alias="groupDescription")] = None
    group_ids: Annotated[list[str] | None, Field(alias="groupIds")] = None


class AdverseEvent(BaseModel):
    term: str | None = None
    organ_system: Annotated[str | None, Field(alias="organSystem")] = None
    source_vocabulary: Annotated[str | None, Field(alias="sourceVocabulary")] = None
    assessment_type: Annotated[EventAssessment | None, Field(alias="assessmentType")] = None
    notes: str | None = None
    stats: list[EventStats] | None = None


class Denom(BaseModel):
    units: str | None = None
    counts: list[DenomCount] | None = None


class LargeDoc(BaseModel):
    type_abbrev: Annotated[str | None, Field(alias="typeAbbrev")] = None
    has_protocol: Annotated[bool | None, Field(alias="hasProtocol")] = None
    has_sap: Annotated[bool | None, Field(alias="hasSap")] = None
    has_icf: Annotated[bool | None, Field(alias="hasIcf")] = None
    label: str | None = None
    date: date_aliased | None = None
    upload_date: Annotated[DateTimeMinutes | None, Field(alias="uploadDate")] = None
    filename: str | None = None
    size: int | None = None


class DropWithdraw(BaseModel):
    type: str | None = None
    comment: str | None = None
    reasons: list[FlowStats] | None = None


class MeasureCategory(BaseModel):
    title: str | None = None
    measurements: list[Measurement] | None = None


class FlowMilestone(BaseModel):
    type: str | None = None
    comment: str | None = None
    achievements: list[FlowStats] | None = None


class FieldValuesStats(
    RootModel[EnumStats | StringStats | DateStats | IntegerStats | NumberStats | BooleanStats]
):
    root: EnumStats | StringStats | DateStats | IntegerStats | NumberStats | BooleanStats


class SearchDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    areas: list[SearchArea]
    name: str


class SearchDocumentList(RootModel[list[SearchDocument]]):
    root: list[SearchDocument]


class IdentificationModule(BaseModel):
    nct_id: Annotated[Nct | None, Field(alias="nctId")] = None
    nct_id_aliases: Annotated[list[Nct] | None, Field(alias="nctIdAliases")] = None
    org_study_id_info: Annotated[OrgStudyIdInfo | None, Field(alias="orgStudyIdInfo")] = None
    secondary_id_infos: Annotated[list[SecondaryIdInfo] | None, Field(alias="secondaryIdInfos")] = (
        None
    )
    brief_title: Annotated[str | None, Field(alias="briefTitle")] = None
    official_title: Annotated[str | None, Field(alias="officialTitle")] = None
    acronym: str | None = None
    organization: Organization | None = None


class StatusModule(BaseModel):
    status_verified_date: Annotated[PartialDate | None, Field(alias="statusVerifiedDate")] = None
    overall_status: Annotated[Status | None, Field(alias="overallStatus")] = None
    last_known_status: Annotated[Status | None, Field(alias="lastKnownStatus")] = None
    delayed_posting: Annotated[bool | None, Field(alias="delayedPosting")] = None
    why_stopped: Annotated[str | None, Field(alias="whyStopped")] = None
    expanded_access_info: Annotated[
        ExpandedAccessInfo | None, Field(alias="expandedAccessInfo")
    ] = None
    start_date_struct: Annotated[PartialDateStruct | None, Field(alias="startDateStruct")] = None
    primary_completion_date_struct: Annotated[
        PartialDateStruct | None, Field(alias="primaryCompletionDateStruct")
    ] = None
    completion_date_struct: Annotated[
        PartialDateStruct | None, Field(alias="completionDateStruct")
    ] = None
    study_first_submit_date: Annotated[date_aliased | None, Field(alias="studyFirstSubmitDate")] = (
        None
    )
    study_first_submit_qc_date: Annotated[
        date_aliased | None, Field(alias="studyFirstSubmitQcDate")
    ] = None
    study_first_post_date_struct: Annotated[
        DateStruct | None, Field(alias="studyFirstPostDateStruct")
    ] = None
    results_waived: Annotated[bool | None, Field(alias="resultsWaived")] = None
    results_first_submit_date: Annotated[
        date_aliased | None, Field(alias="resultsFirstSubmitDate")
    ] = None
    results_first_submit_qc_date: Annotated[
        date_aliased | None, Field(alias="resultsFirstSubmitQcDate")
    ] = None
    results_first_post_date_struct: Annotated[
        DateStruct | None, Field(alias="resultsFirstPostDateStruct")
    ] = None
    disp_first_submit_date: Annotated[date_aliased | None, Field(alias="dispFirstSubmitDate")] = (
        None
    )
    disp_first_submit_qc_date: Annotated[
        date_aliased | None, Field(alias="dispFirstSubmitQcDate")
    ] = None
    disp_first_post_date_struct: Annotated[
        DateStruct | None, Field(alias="dispFirstPostDateStruct")
    ] = None
    last_update_submit_date: Annotated[date_aliased | None, Field(alias="lastUpdateSubmitDate")] = (
        None
    )
    last_update_post_date_struct: Annotated[
        DateStruct | None, Field(alias="lastUpdatePostDateStruct")
    ] = None


class SponsorCollaboratorsModule(BaseModel):
    responsible_party: Annotated[ResponsibleParty | None, Field(alias="responsibleParty")] = None
    lead_sponsor: Annotated[Sponsor | None, Field(alias="leadSponsor")] = None
    collaborators: list[Sponsor] | None = None


class ArmsInterventionsModule(BaseModel):
    arm_groups: Annotated[list[ArmGroup] | None, Field(alias="armGroups")] = None
    interventions: list[Intervention] | None = None


class ContactsLocationsModule(BaseModel):
    central_contacts: Annotated[list[Contact] | None, Field(alias="centralContacts")] = None
    overall_officials: Annotated[list[Official] | None, Field(alias="overallOfficials")] = None
    locations: list[Location] | None = None


class ReferencesModule(BaseModel):
    references: list[Reference] | None = None
    see_also_links: Annotated[list[SeeAlsoLink] | None, Field(alias="seeAlsoLinks")] = None
    avail_ipds: Annotated[list[AvailIpd] | None, Field(alias="availIpds")] = None


class MoreInfoModule(BaseModel):
    limitations_and_caveats: Annotated[
        LimitationsAndCaveats | None, Field(alias="limitationsAndCaveats")
    ] = None
    certain_agreement: Annotated[CertainAgreement | None, Field(alias="certainAgreement")] = None
    point_of_contact: Annotated[PointOfContact | None, Field(alias="pointOfContact")] = None


class UnpostedAnnotation(BaseModel):
    unposted_responsible_party: Annotated[str | None, Field(alias="unpostedResponsibleParty")] = (
        None
    )
    unposted_events: Annotated[list[UnpostedEvent] | None, Field(alias="unpostedEvents")] = None


class ViolationAnnotation(BaseModel):
    violation_events: Annotated[list[ViolationEvent] | None, Field(alias="violationEvents")] = None


class FirstMcpInfo(BaseModel):
    post_date_struct: Annotated[DateStruct | None, Field(alias="postDateStruct")] = None


class AdverseEventsModule(BaseModel):
    frequency_threshold: Annotated[str | None, Field(alias="frequencyThreshold")] = None
    time_frame: Annotated[str | None, Field(alias="timeFrame")] = None
    description: str | None = None
    all_cause_mortality_comment: Annotated[str | None, Field(alias="allCauseMortalityComment")] = (
        None
    )
    event_groups: Annotated[list[EventGroup] | None, Field(alias="eventGroups")] = None
    serious_events: Annotated[list[AdverseEvent] | None, Field(alias="seriousEvents")] = None
    other_events: Annotated[list[AdverseEvent] | None, Field(alias="otherEvents")] = None


class DesignInfo(BaseModel):
    allocation: DesignAllocation | None = None
    intervention_model: Annotated[
        InterventionalAssignment | None, Field(alias="interventionModel")
    ] = None
    intervention_model_description: Annotated[
        str | None, Field(alias="interventionModelDescription")
    ] = None
    primary_purpose: Annotated[PrimaryPurpose | None, Field(alias="primaryPurpose")] = None
    observational_model: Annotated[ObservationalModel | None, Field(alias="observationalModel")] = (
        None
    )
    time_perspective: Annotated[DesignTimePerspective | None, Field(alias="timePerspective")] = None
    masking_info: Annotated[MaskingBlock | None, Field(alias="maskingInfo")] = None


class LargeDocumentModule(BaseModel):
    no_sap: Annotated[bool | None, Field(alias="noSap")] = None
    large_docs: Annotated[list[LargeDoc] | None, Field(alias="largeDocs")] = None


class BrowseModule(BaseModel):
    meshes: list[Mesh] | None = None
    ancestors: list[Mesh] | None = None
    browse_leaves: Annotated[list[BrowseLeaf] | None, Field(alias="browseLeaves")] = None
    browse_branches: Annotated[list[BrowseBranch] | None, Field(alias="browseBranches")] = None


class FlowPeriod(BaseModel):
    title: str | None = None
    milestones: list[FlowMilestone] | None = None
    drop_withdraws: Annotated[list[DropWithdraw] | None, Field(alias="dropWithdraws")] = None


class MeasureClass(BaseModel):
    title: str | None = None
    denoms: list[Denom] | None = None
    categories: list[MeasureCategory] | None = None


class BaselineMeasure(BaseModel):
    title: str | None = None
    description: str | None = None
    population_description: Annotated[str | None, Field(alias="populationDescription")] = None
    param_type: Annotated[MeasureParam | None, Field(alias="paramType")] = None
    dispersion_type: Annotated[MeasureDispersionType | None, Field(alias="dispersionType")] = None
    unit_of_measure: Annotated[str | None, Field(alias="unitOfMeasure")] = None
    calculate_pct: Annotated[bool | None, Field(alias="calculatePct")] = None
    denom_units_selected: Annotated[str | None, Field(alias="denomUnitsSelected")] = None
    denoms: list[Denom] | None = None
    classes: list[MeasureClass] | None = None


class FieldValuesStatsList(RootModel[list[FieldValuesStats]]):
    root: list[FieldValuesStats]


class DocumentSection(BaseModel):
    large_document_module: Annotated[
        LargeDocumentModule | None, Field(alias="largeDocumentModule")
    ] = None


class DesignModule(BaseModel):
    study_type: Annotated[StudyType | None, Field(alias="studyType")] = None
    n_ptrs_to_this_exp_acc_nct_id: Annotated[int | None, Field(alias="nPtrsToThisExpAccNctId")] = (
        None
    )
    expanded_access_types: Annotated[
        ExpandedAccessTypes | None, Field(alias="expandedAccessTypes")
    ] = None
    patient_registry: Annotated[bool | None, Field(alias="patientRegistry")] = None
    target_duration: Annotated[
        str | None,
        Field(
            alias="targetDuration",
            pattern="^\\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$",
        ),
    ] = None
    phases: list[Phase] | None = None
    design_info: Annotated[DesignInfo | None, Field(alias="designInfo")] = None
    bio_spec: Annotated[BioSpec | None, Field(alias="bioSpec")] = None
    enrollment_info: Annotated[EnrollmentInfo | None, Field(alias="enrollmentInfo")] = None


class AnnotationModule(BaseModel):
    unposted_annotation: Annotated[UnpostedAnnotation | None, Field(alias="unpostedAnnotation")] = (
        None
    )
    violation_annotation: Annotated[
        ViolationAnnotation | None, Field(alias="violationAnnotation")
    ] = None


class SubmissionTracking(BaseModel):
    estimated_results_first_submit_date: Annotated[
        date_aliased | None, Field(alias="estimatedResultsFirstSubmitDate")
    ] = None
    first_mcp_info: Annotated[FirstMcpInfo | None, Field(alias="firstMcpInfo")] = None
    submission_infos: Annotated[list[SubmissionInfo] | None, Field(alias="submissionInfos")] = None


class OutcomeMeasure(BaseModel):
    type: OutcomeMeasureType | None = None
    title: str | None = None
    description: str | None = None
    population_description: Annotated[str | None, Field(alias="populationDescription")] = None
    reporting_status: Annotated[ReportingStatus | None, Field(alias="reportingStatus")] = None
    anticipated_posting_date: Annotated[
        PartialDate | None, Field(alias="anticipatedPostingDate")
    ] = None
    param_type: Annotated[MeasureParam | None, Field(alias="paramType")] = None
    dispersion_type: Annotated[str | None, Field(alias="dispersionType")] = None
    unit_of_measure: Annotated[str | None, Field(alias="unitOfMeasure")] = None
    calculate_pct: Annotated[bool | None, Field(alias="calculatePct")] = None
    time_frame: Annotated[str | None, Field(alias="timeFrame")] = None
    type_units_analyzed: Annotated[str | None, Field(alias="typeUnitsAnalyzed")] = None
    denom_units_selected: Annotated[str | None, Field(alias="denomUnitsSelected")] = None
    groups: list[MeasureGroup] | None = None
    denoms: list[Denom] | None = None
    classes: list[MeasureClass] | None = None
    analyses: list[MeasureAnalysis] | None = None


class BaselineCharacteristicsModule(BaseModel):
    population_description: Annotated[str | None, Field(alias="populationDescription")] = None
    type_units_analyzed: Annotated[str | None, Field(alias="typeUnitsAnalyzed")] = None
    groups: list[MeasureGroup] | None = None
    denoms: list[Denom] | None = None
    measures: list[BaselineMeasure] | None = None


class ParticipantFlowModule(BaseModel):
    pre_assignment_details: Annotated[str | None, Field(alias="preAssignmentDetails")] = None
    recruitment_details: Annotated[str | None, Field(alias="recruitmentDetails")] = None
    type_units_analyzed: Annotated[str | None, Field(alias="typeUnitsAnalyzed")] = None
    groups: list[FlowGroup] | None = None
    periods: list[FlowPeriod] | None = None


class ProtocolSection(BaseModel):
    identification_module: Annotated[
        IdentificationModule | None, Field(alias="identificationModule")
    ] = None
    status_module: Annotated[StatusModule | None, Field(alias="statusModule")] = None
    sponsor_collaborators_module: Annotated[
        SponsorCollaboratorsModule | None, Field(alias="sponsorCollaboratorsModule")
    ] = None
    oversight_module: Annotated[OversightModule | None, Field(alias="oversightModule")] = None
    description_module: Annotated[DescriptionModule | None, Field(alias="descriptionModule")] = None
    conditions_module: Annotated[ConditionsModule | None, Field(alias="conditionsModule")] = None
    design_module: Annotated[DesignModule | None, Field(alias="designModule")] = None
    arms_interventions_module: Annotated[
        ArmsInterventionsModule | None, Field(alias="armsInterventionsModule")
    ] = None
    outcomes_module: Annotated[OutcomesModule | None, Field(alias="outcomesModule")] = None
    eligibility_module: Annotated[EligibilityModule | None, Field(alias="eligibilityModule")] = None
    contacts_locations_module: Annotated[
        ContactsLocationsModule | None, Field(alias="contactsLocationsModule")
    ] = None
    references_module: Annotated[ReferencesModule | None, Field(alias="referencesModule")] = None
    ipd_sharing_statement_module: Annotated[
        IpdSharingStatementModule | None, Field(alias="ipdSharingStatementModule")
    ] = None


class AnnotationSection(BaseModel):
    annotation_module: Annotated[AnnotationModule | None, Field(alias="annotationModule")] = None


class OutcomeMeasuresModule(BaseModel):
    outcome_measures: Annotated[list[OutcomeMeasure] | None, Field(alias="outcomeMeasures")] = None


class MiscInfoModule(BaseModel):
    version_holder: Annotated[date_aliased | None, Field(alias="versionHolder")] = None
    removed_countries: Annotated[list[str] | None, Field(alias="removedCountries")] = None
    submission_tracking: Annotated[SubmissionTracking | None, Field(alias="submissionTracking")] = (
        None
    )


class ResultsSection(BaseModel):
    participant_flow_module: Annotated[
        ParticipantFlowModule | None, Field(alias="participantFlowModule")
    ] = None
    baseline_characteristics_module: Annotated[
        BaselineCharacteristicsModule | None, Field(alias="baselineCharacteristicsModule")
    ] = None
    outcome_measures_module: Annotated[
        OutcomeMeasuresModule | None, Field(alias="outcomeMeasuresModule")
    ] = None
    adverse_events_module: Annotated[
        AdverseEventsModule | None, Field(alias="adverseEventsModule")
    ] = None
    more_info_module: Annotated[MoreInfoModule | None, Field(alias="moreInfoModule")] = None


class DerivedSection(BaseModel):
    misc_info_module: Annotated[MiscInfoModule | None, Field(alias="miscInfoModule")] = None
    condition_browse_module: Annotated[
        BrowseModule | None, Field(alias="conditionBrowseModule")
    ] = None
    intervention_browse_module: Annotated[
        BrowseModule | None, Field(alias="interventionBrowseModule")
    ] = None


class Study(BaseModel):
    protocol_section: Annotated[ProtocolSection | None, Field(alias="protocolSection")] = None
    results_section: Annotated[ResultsSection | None, Field(alias="resultsSection")] = None
    annotation_section: Annotated[AnnotationSection | None, Field(alias="annotationSection")] = None
    document_section: Annotated[DocumentSection | None, Field(alias="documentSection")] = None
    derived_section: Annotated[DerivedSection | None, Field(alias="derivedSection")] = None
    has_results: Annotated[bool | None, Field(alias="hasResults")] = None


class StudyList(RootModel[list[Study]]):
    """
    `study` field values of type `markup` are in markdown format.

    """

    root: Annotated[
        list[Study],
        Field(
            description="`study` field values of type `markup` are in markdown format.\n",
            title="Array of studies",
        ),
    ]


class PagedStudies(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    next_page_token: Annotated[str | None, Field(alias="nextPageToken")] = None
    studies: StudyList
    total_count: Annotated[int | None, Field(alias="totalCount")] = None


FieldNode.model_rebuild()
