/**
 * The contract between backend and frontend.
 *
 * Mirrors src/scrutatio/matching/schema.py, src/scrutatio/app.py and
 * src/scrutatio/utils/errors.py. The
 * wire format is snake_case on both sides deliberately: Python emits it
 * natively, so there is no alias configuration to get wrong and no field that
 * silently arrives as `undefined`.
 *
 * Generated by hand, kept in step by review. If these ever drift, the Python
 * side is the source of truth — it is what the API actually serialises.
 */

/** The 20 criterion categories. Derived from data, not invented: an initial
 *  nine-category taxonomy left 23.6% of criteria in `other`, and `other` cannot
 *  be matched against a patient, so the bucket is a direct cap on recall. */
export type CriterionKind =
  // what the patient has
  | "condition"
  | "stage"
  | "biomarker"
  | "comorbidity"
  | "infection"
  // measurements
  | "lab"
  | "organ_function"
  | "ecog"
  | "age"
  | "life_expectancy"
  | "measurable_disease"
  // treatment history and constraints
  | "prior_therapy"
  | "concurrent_therapy"
  | "procedure"
  | "washout"
  | "allergy"
  // administrative
  | "reproductive"
  | "consent"
  | "compliance"
  | "other";

/** The same twenty, as a value — grouped the way the extraction prompt groups
 *  them, so a filter list reads in the order a clinician thinks. */
export const CRITERION_KINDS: readonly CriterionKind[] = [
  'condition',
  'stage',
  'biomarker',
  'comorbidity',
  'infection',
  'lab',
  'organ_function',
  'ecog',
  'age',
  'life_expectancy',
  'measurable_disease',
  'prior_therapy',
  'concurrent_therapy',
  'procedure',
  'washout',
  'allergy',
  'reproductive',
  'consent',
  'compliance',
  'other',
]

/**
 * Categories a patient description structurally cannot answer.
 *
 * Measured on real data: these came back 100% `unclear`, because no vignette
 * states whether someone can consent or uses contraception. Collapse them by
 * default — otherwise eleven undecidable rows bury the four that matter.
 */
export const ADMINISTRATIVE_KINDS: readonly CriterionKind[] = [
  "consent",
  "compliance",
  "reproductive",
];

/** Three states, and the third is not a hedge. `unclear` means the criterion
 *  cannot be decided from the description given — which is precisely the item a
 *  human should look at, so it is a useful answer rather than a missing one. */
export type Verdict = "met" | "not_met" | "unclear";

export interface CriterionVerdict {
  /** Stable key within the trial, carried through from the Silver layer. */
  ordinal: number;
  /** The criterion as a single self-contained sentence. */
  text: string;
  kind: CriterionKind;
  is_exclusion: boolean;
  verdict: Verdict;
  /** Why this verdict. Never empty — a ranking without a reason invites trust
   *  it has not earned, which is worse than no answer. Render it. */
  rationale: string;
}

/** Why the trial was retrieved at all: the nearest criterion by embedding. */
export interface MatchedOn {
  ordinal: number;
  text: string;
  /** Cosine similarity, -1..1. */
  score: number;
}

export interface VerdictCounts {
  met: number;
  not_met: number;
  unclear: number;
}

export interface TrialMatch {
  nct_id: string;
  title: string;
  phase: string | null;
  overall_status: string;
  locations: string[];
  matched_on: MatchedOn;
  counts: VerdictCounts;
  criteria: CriterionVerdict[];
}

export interface MatchResponse {
  query: string;
  /** ISO 8601. */
  generated_at: string;
  model: string;
  /** Carried in the payload rather than hardcoded in the UI, so a refactor
   *  cannot drop it. Must be visible without scrolling. */
  disclaimer: string;
  trials: TrialMatch[];
}

export interface MatchRequest {
  /** Synthetic vignettes only. Never real patient data. */
  text: string;
  k?: number;
}

// --- corpus explorer -------------------------------------------------------

export interface LayerCounts {
  bronze_trials: number;
  newest_update: string | null;
  silver_trials: number;
  silver_criteria: number;
  silver_failed: number;
  gold_vectors: number;
  embedding_model: string;
  signature: string;
  /** Absolute path of the database these counts came from.
   *
   *  Worth showing when everything reads zero: that is indistinguishable from
   *  "the pipeline has not run", and once meant the server had been started from
   *  the wrong directory and created an empty database beside itself. */
  database: string;
}

export interface CriterionRow {
  nct_id: string;
  ordinal: number;
  text: string;
  kind: CriterionKind;
  is_exclusion: boolean;
}

export interface CriterionPage {
  total: number;
  offset: number;
  limit: number;
  rows: CriterionRow[];
}

export interface Health {
  status: string;
  signature: string;
}

export interface ApiIndex {
  name: string;
  version: string;
  disclaimer: string;
  /** "GET /health" -> what it does. The base URL is a directory. */
  endpoints: Record<string, string>;
}

// --- errors ----------------------------------------------------------------

/**
 * Codes the backend emits. Branch on these, never on `detail`.
 *
 * `detail` is written for a human and will be reworded; a UI that pattern-matches
 * English sentences breaks the moment someone improves one. The `(string & {})`
 * arm keeps autocomplete for the known codes while still accepting the
 * `http_404`-style codes the framework handlers generate.
 */
export type ApiErrorCode =
  /** A pipeline run holds the DuckDB file. DuckDB permits one process, so this is
   *  expected during a backfill, extraction or embedding pass. Retry later. */
  | "database_busy"
  /** The Gold layer has no vectors yet — `scrutatio embed` has not run. */
  | "gold_empty"
  /** No OPENROUTER_API_KEY on the server, so candidates cannot be judged. */
  | "openrouter_unconfigured"
  /** sentence-transformers is not installed on the server. */
  | "encoder_unavailable"
  /** OpenRouter failed. 502 — the fault is upstream, so retrying may work. */
  | "upstream_failed"
  /** The database raised something other than the lock. */
  | "storage_error"
  /** The request body did not match. `detail` names the field. */
  | "validation_error"
  /** Unmapped server failure. `detail` deliberately says nothing useful; quote
   *  `request_id` when reporting it. */
  | "internal_error"
  | (string & {});

/**
 * The shape of every non-2xx response.
 *
 * Mirrors `ErrorBody` in src/scrutatio/utils/errors.py.
 */
export interface ErrorBody {
  code: ApiErrorCode;
  /** Human-readable. Show it; do not parse it. */
  detail: string;
  /** Also returned in the `X-Request-ID` header, and logged server-side with the
   *  traceback. This is what turns "it broke" into a diagnosable report. */
  request_id: string;
}

export const trialUrl = (nctId: string): string =>
  `https://clinicaltrials.gov/study/${nctId}`;
