"""Local persistence in a single DuckDB file."""

from scrutatio.storage.bronze import (
    BRONZE_TABLE,
    DEFAULT_BATCH_SIZE,
    RUNS_TABLE,
    TrialMeta,
    bronze_count,
    bronze_max_update,
    ensure_storage,
    finish_run,
    safe_watermark,
    start_run,
    trial_metadata,
    write_bronze,
)
from scrutatio.storage.cache import (
    CACHE_TABLE,
    cache_stats,
    cached_verdicts,
    ensure_cache,
    query_hash,
    store_verdicts,
)
from scrutatio.storage.db import IN_MEMORY, DatabaseBusyError, connect, database
from scrutatio.storage.gold import (
    GOLD_TABLE,
    ensure_gold,
    gold_stats,
    pending_criteria,
    search_criteria,
    write_embeddings,
)
from scrutatio.storage.silver import (
    FAILURES_TABLE,
    SILVER_TABLE,
    ensure_silver,
    extraction_signature,
    pending_trials,
    silver_stats,
    trial_criteria,
    write_silver,
)

__all__ = [
    "BRONZE_TABLE",
    "CACHE_TABLE",
    "DEFAULT_BATCH_SIZE",
    "FAILURES_TABLE",
    "GOLD_TABLE",
    "IN_MEMORY",
    "RUNS_TABLE",
    "SILVER_TABLE",
    "DatabaseBusyError",
    "TrialMeta",
    "bronze_count",
    "bronze_max_update",
    "cache_stats",
    "cached_verdicts",
    "connect",
    "database",
    "ensure_cache",
    "ensure_gold",
    "ensure_silver",
    "ensure_storage",
    "extraction_signature",
    "finish_run",
    "gold_stats",
    "pending_criteria",
    "pending_trials",
    "query_hash",
    "safe_watermark",
    "search_criteria",
    "silver_stats",
    "start_run",
    "store_verdicts",
    "trial_criteria",
    "trial_metadata",
    "write_bronze",
    "write_embeddings",
    "write_silver",
]
