# generated by datamodel-codegen:
#   filename:  ctgov-openapi.yaml

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class WebLink(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: str
    url: str


class SearchPart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    is_enum: bool = Field(..., alias="isEnum")
    is_synonyms: bool = Field(..., alias="isSynonyms")
    pieces: list[str]
    type: str
    weight: float


class EnumItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    exceptions: dict[str, Any] | None = None
    legacy_value: str = Field(..., alias="legacyValue")
    value: str


class StudySize(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    size_bytes: int = Field(..., alias="sizeBytes")


class DistItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    size_range: str = Field(..., alias="sizeRange")
    studies_count: int = Field(..., alias="studiesCount")


class ListSize(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    size: int
    studies_count: int = Field(..., alias="studiesCount")


class ValueCount(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    studies_count: int = Field(..., alias="studiesCount")
    value: str


class FieldStatsType(StrEnum):
    enum = "ENUM"
    string = "STRING"
    date = "DATE"
    integer = "INTEGER"
    number = "NUMBER"
    boolean = "BOOLEAN"


class LongestString(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    length: int
    nct_id: str = Field(..., alias="nctId")
    value: str


class DateStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    formats: list[str]
    max: str | None = None
    min: str | None = None
    missing_studies_count: int = Field(..., alias="missingStudiesCount")
    piece: str
    type: FieldStatsType


class IntegerStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    avg: float | None = None
    field: str
    max: int | None = None
    min: int | None = None
    missing_studies_count: int = Field(..., alias="missingStudiesCount")
    piece: str
    type: FieldStatsType


class NumberStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    avg: float | None = None
    field: str
    max: float | None = None
    min: float | None = None
    missing_studies_count: int = Field(..., alias="missingStudiesCount")
    piece: str
    type: FieldStatsType


class BooleanStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    false_count: int = Field(..., alias="falseCount")
    field: str
    missing_studies_count: int = Field(..., alias="missingStudiesCount")
    piece: str
    true_count: int = Field(..., alias="trueCount")
    type: FieldStatsType


class Version(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api_version: str = Field(..., alias="apiVersion")
    data_timestamp: str | None = Field(None, alias="dataTimestamp")


class OversightModule(BaseModel):
    oversight_has_dmc: bool | None = Field(None, alias="oversightHasDmc")
    is_fda_regulated_drug: bool | None = Field(None, alias="isFdaRegulatedDrug")
    is_fda_regulated_device: bool | None = Field(None, alias="isFdaRegulatedDevice")
    is_unapproved_device: bool | None = Field(None, alias="isUnapprovedDevice")
    is_ppsd: bool | None = Field(None, alias="isPpsd")
    is_us_export: bool | None = Field(None, alias="isUsExport")
    fdaaa801_violation: bool | None = Field(None, alias="fdaaa801Violation")


class DescriptionModule(BaseModel):
    brief_summary: str | None = Field(None, alias="briefSummary")
    detailed_description: str | None = Field(None, alias="detailedDescription")


class ConditionsModule(BaseModel):
    conditions: list[str] | None = None
    keywords: list[str] | None = None


class SeeAlsoLink(BaseModel):
    label: str | None = None
    url: str | None = None


class ExpandedAccessTypes(BaseModel):
    individual: bool | None = None
    intermediate: bool | None = None
    treatment: bool | None = None


class AvailIpd(BaseModel):
    id: str | None = None
    type: str | None = None
    url: str | None = None
    comment: str | None = None


class LimitationsAndCaveats(BaseModel):
    description: str | None = None


class SubmissionInfo(BaseModel):
    release_date: date_aliased | None = Field(None, alias="releaseDate")
    unrelease_date: date_aliased | None = Field(None, alias="unreleaseDate")
    unrelease_date_unknown: bool | None = Field(None, alias="unreleaseDateUnknown")
    reset_date: date_aliased | None = Field(None, alias="resetDate")
    mcp_release_n: int | None = Field(None, alias="mcpReleaseN")


class PointOfContact(BaseModel):
    title: str | None = None
    organization: str | None = None
    email: str | None = None
    phone: str | None = None
    phone_ext: str | None = Field(None, alias="phoneExt")


class Outcome(BaseModel):
    measure: str | None = None
    description: str | None = None
    time_frame: str | None = Field(None, alias="timeFrame")


class EventGroup(BaseModel):
    id: str | None = None
    title: str | None = None
    description: str | None = None
    deaths_num_affected: int | None = Field(None, alias="deathsNumAffected")
    deaths_num_at_risk: int | None = Field(None, alias="deathsNumAtRisk")
    serious_num_affected: int | None = Field(None, alias="seriousNumAffected")
    serious_num_at_risk: int | None = Field(None, alias="seriousNumAtRisk")
    other_num_affected: int | None = Field(None, alias="otherNumAffected")
    other_num_at_risk: int | None = Field(None, alias="otherNumAtRisk")


class Mesh(BaseModel):
    id: str | None = None
    term: str | None = None


class FlowGroup(BaseModel):
    id: str | None = None
    title: str | None = None
    description: str | None = None


class Retraction(BaseModel):
    pmid: str | None = None
    source: str | None = None


class MeasureGroup(BaseModel):
    id: str | None = None
    title: str | None = None
    description: str | None = None


class BrowseBranch(BaseModel):
    abbrev: str | None = None
    name: str | None = None


class DenomCount(BaseModel):
    group_id: str | None = Field(None, alias="groupId")
    value: str | None = None


class EventStats(BaseModel):
    group_id: str | None = Field(None, alias="groupId")
    num_events: int | None = Field(None, alias="numEvents")
    num_affected: int | None = Field(None, alias="numAffected")
    num_at_risk: int | None = Field(None, alias="numAtRisk")


class FlowStats(BaseModel):
    group_id: str | None = Field(None, alias="groupId")
    comment: str | None = None
    num_subjects: str | None = Field(None, alias="numSubjects")
    num_units: str | None = Field(None, alias="numUnits")


class Measurement(BaseModel):
    group_id: str | None = Field(None, alias="groupId")
    value: str | None = None
    spread: str | None = None
    lower_limit: str | None = Field(None, alias="lowerLimit")
    upper_limit: str | None = Field(None, alias="upperLimit")
    comment: str | None = None


class Status(StrEnum):
    active_not_recruiting = "ACTIVE_NOT_RECRUITING"
    completed = "COMPLETED"
    enrolling_by_invitation = "ENROLLING_BY_INVITATION"
    not_yet_recruiting = "NOT_YET_RECRUITING"
    recruiting = "RECRUITING"
    suspended = "SUSPENDED"
    terminated = "TERMINATED"
    withdrawn = "WITHDRAWN"
    available = "AVAILABLE"
    no_longer_available = "NO_LONGER_AVAILABLE"
    temporarily_not_available = "TEMPORARILY_NOT_AVAILABLE"
    approved_for_marketing = "APPROVED_FOR_MARKETING"
    withheld = "WITHHELD"
    unknown = "UNKNOWN"


class StudyType(StrEnum):
    expanded_access = "EXPANDED_ACCESS"
    interventional = "INTERVENTIONAL"
    observational = "OBSERVATIONAL"


class Phase(StrEnum):
    na = "NA"
    early_phase1 = "EARLY_PHASE1"
    phase1 = "PHASE1"
    phase2 = "PHASE2"
    phase3 = "PHASE3"
    phase4 = "PHASE4"


class Sex(StrEnum):
    female = "FEMALE"
    male = "MALE"
    all = "ALL"


class StandardAge(StrEnum):
    child = "CHILD"
    adult = "ADULT"
    older_adult = "OLDER_ADULT"


class SamplingMethod(StrEnum):
    probability_sample = "PROBABILITY_SAMPLE"
    non_probability_sample = "NON_PROBABILITY_SAMPLE"


class IpdSharing(StrEnum):
    yes = "YES"
    no = "NO"
    undecided = "UNDECIDED"


class IpdSharingInfoType(StrEnum):
    study_protocol = "STUDY_PROTOCOL"
    sap = "SAP"
    icf = "ICF"
    csr = "CSR"
    analytic_code = "ANALYTIC_CODE"


class OrgStudyIdType(StrEnum):
    nih = "NIH"
    fda = "FDA"
    va = "VA"
    cdc = "CDC"
    ahrq = "AHRQ"
    samhsa = "SAMHSA"


class SecondaryIdType(StrEnum):
    nih = "NIH"
    fda = "FDA"
    va = "VA"
    cdc = "CDC"
    ahrq = "AHRQ"
    samhsa = "SAMHSA"
    other_grant = "OTHER_GRANT"
    eudract_number = "EUDRACT_NUMBER"
    ctis = "CTIS"
    registry = "REGISTRY"
    other = "OTHER"


class AgencyClass(StrEnum):
    nih = "NIH"
    fed = "FED"
    other_gov = "OTHER_GOV"
    indiv = "INDIV"
    industry = "INDUSTRY"
    network = "NETWORK"
    ambig = "AMBIG"
    other = "OTHER"
    unknown = "UNKNOWN"


class ExpandedAccessStatus(StrEnum):
    available = "AVAILABLE"
    no_longer_available = "NO_LONGER_AVAILABLE"
    temporarily_not_available = "TEMPORARILY_NOT_AVAILABLE"
    approved_for_marketing = "APPROVED_FOR_MARKETING"


class DateType(StrEnum):
    actual = "ACTUAL"
    estimated = "ESTIMATED"


class ResponsiblePartyType(StrEnum):
    sponsor = "SPONSOR"
    principal_investigator = "PRINCIPAL_INVESTIGATOR"
    sponsor_investigator = "SPONSOR_INVESTIGATOR"


class DesignAllocation(StrEnum):
    randomized = "RANDOMIZED"
    non_randomized = "NON_RANDOMIZED"
    na = "NA"


class InterventionalAssignment(StrEnum):
    single_group = "SINGLE_GROUP"
    parallel = "PARALLEL"
    crossover = "CROSSOVER"
    factorial = "FACTORIAL"
    sequential = "SEQUENTIAL"


class PrimaryPurpose(StrEnum):
    treatment = "TREATMENT"
    prevention = "PREVENTION"
    diagnostic = "DIAGNOSTIC"
    ect = "ECT"
    supportive_care = "SUPPORTIVE_CARE"
    screening = "SCREENING"
    health_services_research = "HEALTH_SERVICES_RESEARCH"
    basic_science = "BASIC_SCIENCE"
    device_feasibility = "DEVICE_FEASIBILITY"
    other = "OTHER"


class ObservationalModel(StrEnum):
    cohort = "COHORT"
    case_control = "CASE_CONTROL"
    case_only = "CASE_ONLY"
    case_crossover = "CASE_CROSSOVER"
    ecologic_or_community = "ECOLOGIC_OR_COMMUNITY"
    family_based = "FAMILY_BASED"
    defined_population = "DEFINED_POPULATION"
    natural_history = "NATURAL_HISTORY"
    other = "OTHER"


class DesignTimePerspective(StrEnum):
    retrospective = "RETROSPECTIVE"
    prospective = "PROSPECTIVE"
    cross_sectional = "CROSS_SECTIONAL"
    other = "OTHER"


class BioSpecRetention(StrEnum):
    none_retained = "NONE_RETAINED"
    samples_with_dna = "SAMPLES_WITH_DNA"
    samples_without_dna = "SAMPLES_WITHOUT_DNA"


class EnrollmentType(StrEnum):
    actual = "ACTUAL"
    estimated = "ESTIMATED"


class ArmGroupType(StrEnum):
    experimental = "EXPERIMENTAL"
    active_comparator = "ACTIVE_COMPARATOR"
    placebo_comparator = "PLACEBO_COMPARATOR"
    sham_comparator = "SHAM_COMPARATOR"
    no_intervention = "NO_INTERVENTION"
    other = "OTHER"


class InterventionType(StrEnum):
    behavioral = "BEHAVIORAL"
    biological = "BIOLOGICAL"
    combination_product = "COMBINATION_PRODUCT"
    device = "DEVICE"
    diagnostic_test = "DIAGNOSTIC_TEST"
    dietary_supplement = "DIETARY_SUPPLEMENT"
    drug = "DRUG"
    genetic = "GENETIC"
    procedure = "PROCEDURE"
    radiation = "RADIATION"
    other = "OTHER"


class ContactRole(StrEnum):
    study_chair = "STUDY_CHAIR"
    study_director = "STUDY_DIRECTOR"
    principal_investigator = "PRINCIPAL_INVESTIGATOR"
    sub_investigator = "SUB_INVESTIGATOR"
    contact = "CONTACT"


class OfficialRole(StrEnum):
    study_chair = "STUDY_CHAIR"
    study_director = "STUDY_DIRECTOR"
    principal_investigator = "PRINCIPAL_INVESTIGATOR"
    sub_investigator = "SUB_INVESTIGATOR"


class RecruitmentStatus(StrEnum):
    active_not_recruiting = "ACTIVE_NOT_RECRUITING"
    completed = "COMPLETED"
    enrolling_by_invitation = "ENROLLING_BY_INVITATION"
    not_yet_recruiting = "NOT_YET_RECRUITING"
    recruiting = "RECRUITING"
    suspended = "SUSPENDED"
    terminated = "TERMINATED"
    withdrawn = "WITHDRAWN"
    available = "AVAILABLE"


class ReferenceType(StrEnum):
    background = "BACKGROUND"
    result = "RESULT"
    derived = "DERIVED"


class MeasureParam(StrEnum):
    geometric_mean = "GEOMETRIC_MEAN"
    geometric_least_squares_mean = "GEOMETRIC_LEAST_SQUARES_MEAN"
    least_squares_mean = "LEAST_SQUARES_MEAN"
    log_mean = "LOG_MEAN"
    mean = "MEAN"
    median = "MEDIAN"
    number = "NUMBER"
    count_of_participants = "COUNT_OF_PARTICIPANTS"
    count_of_units = "COUNT_OF_UNITS"


class MeasureDispersionType(StrEnum):
    na = "NA"
    standard_deviation = "STANDARD_DEVIATION"
    standard_error = "STANDARD_ERROR"
    inter_quartile_range = "INTER_QUARTILE_RANGE"
    full_range = "FULL_RANGE"
    confidence_80 = "CONFIDENCE_80"
    confidence_90 = "CONFIDENCE_90"
    confidence_95 = "CONFIDENCE_95"
    confidence_975 = "CONFIDENCE_975"
    confidence_99 = "CONFIDENCE_99"
    confidence_other = "CONFIDENCE_OTHER"
    geometric_coefficient = "GEOMETRIC_COEFFICIENT"


class OutcomeMeasureType(StrEnum):
    primary = "PRIMARY"
    secondary = "SECONDARY"
    other_pre_specified = "OTHER_PRE_SPECIFIED"
    post_hoc = "POST_HOC"


class ReportingStatus(StrEnum):
    not_posted = "NOT_POSTED"
    posted = "POSTED"


class EventAssessment(StrEnum):
    non_systematic_assessment = "NON_SYSTEMATIC_ASSESSMENT"
    systematic_assessment = "SYSTEMATIC_ASSESSMENT"


class AgreementRestrictionType(StrEnum):
    lte60 = "LTE60"
    gt60 = "GT60"
    other = "OTHER"


class BrowseLeafRelevance(StrEnum):
    low = "LOW"
    high = "HIGH"


class DesignMasking(StrEnum):
    none = "NONE"
    single = "SINGLE"
    double = "DOUBLE"
    triple = "TRIPLE"
    quadruple = "QUADRUPLE"


class WhoMasked(StrEnum):
    participant = "PARTICIPANT"
    care_provider = "CARE_PROVIDER"
    investigator = "INVESTIGATOR"
    outcomes_assessor = "OUTCOMES_ASSESSOR"


class AnalysisDispersionType(StrEnum):
    standard_deviation = "STANDARD_DEVIATION"
    standard_error_of_mean = "STANDARD_ERROR_OF_MEAN"


class ConfidenceIntervalNumSides(StrEnum):
    one_sided = "ONE_SIDED"
    two_sided = "TWO_SIDED"


class NonInferiorityType(StrEnum):
    superiority = "SUPERIORITY"
    non_inferiority = "NON_INFERIORITY"
    equivalence = "EQUIVALENCE"
    other = "OTHER"
    non_inferiority_or_equivalence = "NON_INFERIORITY_OR_EQUIVALENCE"
    superiority_or_other = "SUPERIORITY_OR_OTHER"
    non_inferiority_or_equivalence_legacy = "NON_INFERIORITY_OR_EQUIVALENCE_LEGACY"
    superiority_or_other_legacy = "SUPERIORITY_OR_OTHER_LEGACY"


class UnpostedEventType(StrEnum):
    reset = "RESET"
    release = "RELEASE"
    unrelease = "UNRELEASE"


class ViolationEventType(StrEnum):
    violation_identified = "VIOLATION_IDENTIFIED"
    correction_confirmed = "CORRECTION_CONFIRMED"
    penalty_imposed = "PENALTY_IMPOSED"
    issues_in_letter_addressed_confirmed = "ISSUES_IN_LETTER_ADDRESSED_CONFIRMED"


class GeoPoint(BaseModel):
    lat: float
    lon: float


class StudiesCsv(RootModel[str]):
    root: str = Field(..., description="Study objects in csv file")


class StudiesZip(RootModel[str]):
    root: str = Field(..., description="Study objects as files in zip archive")


class StudyFhir(BaseModel):
    """
    Study in FHIR JSON format
    """


class Csv(RootModel[str]):
    root: str = Field(..., description="CSV file")


class Nct(RootModel[constr(min_length=11, max_length=11)]):
    root: constr(min_length=11, max_length=11) = Field(..., description="NCT number")


class PartialDate(RootModel[str]):
    root: str = Field(..., description="Date in `yyyy`, `yyyy-MM`, or `yyyy-MM-dd` format")


class DateTimeMinutes(RootModel[str]):
    root: str = Field(..., description="Date and time in `yyyy-MM-dd'T'HH:mm` format")


class GeoName(RootModel[str]):
    root: str = Field(..., description="State/province or city name")


class ErrorMessage(RootModel[str]):
    root: str = Field(..., description="A text message describing an error")


class FieldNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    alt_piece_names: list[str] | None = Field(None, alias="altPieceNames")
    children: list[FieldNode] | None = None
    ded_link: WebLink | None = Field(None, alias="dedLink")
    description: str | None = None
    historic_only: bool | None = Field(None, alias="historicOnly")
    indexed_only: bool | None = Field(None, alias="indexedOnly")
    is_enum: bool | None = Field(None, alias="isEnum")
    max_chars: int | None = Field(None, alias="maxChars")
    name: str
    nested: bool | None = None
    piece: str
    rules: str | None = None
    source_type: str = Field(..., alias="sourceType")
    synonyms: bool | None = None
    title: str | None = None
    type: str


class FieldNodeList(RootModel[list[FieldNode]]):
    root: list[FieldNode]


class SearchArea(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    param: str | None = None
    parts: list[SearchPart]
    ui_label: str | None = Field(None, alias="uiLabel")


class EnumInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pieces: list[str]
    type: str
    values: list[EnumItem]


class EnumInfoList(RootModel[list[EnumInfo]]):
    root: list[EnumInfo]


class GzipStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    average_size_bytes: int = Field(..., alias="averageSizeBytes")
    largest_studies: list[StudySize] = Field(..., alias="largestStudies")
    percentiles: dict[str, Any]
    ranges: list[DistItem]
    total_studies: int = Field(..., alias="totalStudies")


class ListSizes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    max_size: int | None = Field(None, alias="maxSize")
    min_size: int | None = Field(None, alias="minSize")
    piece: str
    top_sizes: list[ListSize] | None = Field(None, alias="topSizes")
    unique_sizes_count: int = Field(..., alias="uniqueSizesCount")


class ListSizesList(RootModel[list[ListSizes]]):
    root: list[ListSizes]


class EnumStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    missing_studies_count: int = Field(..., alias="missingStudiesCount")
    piece: str
    top_values: list[ValueCount] | None = Field(None, alias="topValues")
    type: FieldStatsType
    unique_values_count: int = Field(..., alias="uniqueValuesCount")


class StringStats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field: str
    longest: LongestString | None = None
    missing_studies_count: int = Field(..., alias="missingStudiesCount")
    piece: str
    top_values: list[ValueCount] | None = Field(None, alias="topValues")
    type: FieldStatsType
    unique_values_count: int = Field(..., alias="uniqueValuesCount")


class OutcomesModule(BaseModel):
    primary_outcomes: list[Outcome] | None = Field(None, alias="primaryOutcomes")
    secondary_outcomes: list[Outcome] | None = Field(None, alias="secondaryOutcomes")
    other_outcomes: list[Outcome] | None = Field(None, alias="otherOutcomes")


class EligibilityModule(BaseModel):
    eligibility_criteria: str | None = Field(None, alias="eligibilityCriteria")
    healthy_volunteers: bool | None = Field(None, alias="healthyVolunteers")
    sex: Sex | None = None
    gender_based: bool | None = Field(None, alias="genderBased")
    gender_description: str | None = Field(None, alias="genderDescription")
    minimum_age: (
        constr(
            pattern=r"^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$"
        )
        | None
    ) = Field(None, alias="minimumAge")
    maximum_age: (
        constr(
            pattern=r"^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$"
        )
        | None
    ) = Field(None, alias="maximumAge")
    std_ages: list[StandardAge] | None = Field(None, alias="stdAges")
    study_population: str | None = Field(None, alias="studyPopulation")
    sampling_method: SamplingMethod | None = Field(None, alias="samplingMethod")


class EnrollmentInfo(BaseModel):
    count: int | None = None
    type: EnrollmentType | None = None


class BioSpec(BaseModel):
    retention: BioSpecRetention | None = None
    description: str | None = None


class Intervention(BaseModel):
    type: InterventionType | None = None
    name: str | None = None
    description: str | None = None
    arm_group_labels: list[str] | None = Field(None, alias="armGroupLabels")
    other_names: list[str] | None = Field(None, alias="otherNames")


class SecondaryIdInfo(BaseModel):
    id: str | None = None
    type: SecondaryIdType | None = None
    domain: str | None = None
    link: str | None = None


class DateStruct(BaseModel):
    date: date_aliased | None = None
    type: DateType | None = None


class ExpandedAccessInfo(BaseModel):
    has_expanded_access: bool | None = Field(None, alias="hasExpandedAccess")
    nct_id: Nct | None = Field(None, alias="nctId")
    status_for_nct_id: ExpandedAccessStatus | None = Field(None, alias="statusForNctId")


class ViolationEvent(BaseModel):
    type: ViolationEventType | None = None
    description: str | None = None
    creation_date: date_aliased | None = Field(None, alias="creationDate")
    issued_date: date_aliased | None = Field(None, alias="issuedDate")
    release_date: date_aliased | None = Field(None, alias="releaseDate")
    posted_date: date_aliased | None = Field(None, alias="postedDate")


class ArmGroup(BaseModel):
    label: str | None = None
    type: ArmGroupType | None = None
    description: str | None = None
    intervention_names: list[str] | None = Field(None, alias="interventionNames")


class Organization(BaseModel):
    full_name: str | None = Field(None, alias="fullName")
    class_: AgencyClass | None = Field(None, alias="class")


class IpdSharingStatementModule(BaseModel):
    ipd_sharing: IpdSharing | None = Field(None, alias="ipdSharing")
    description: str | None = None
    info_types: list[IpdSharingInfoType] | None = Field(None, alias="infoTypes")
    time_frame: str | None = Field(None, alias="timeFrame")
    access_criteria: str | None = Field(None, alias="accessCriteria")
    url: str | None = None


class OrgStudyIdInfo(BaseModel):
    id: str | None = None
    type: OrgStudyIdType | None = None
    link: str | None = None


class ResponsibleParty(BaseModel):
    type: ResponsiblePartyType | None = None
    investigator_full_name: str | None = Field(None, alias="investigatorFullName")
    investigator_title: str | None = Field(None, alias="investigatorTitle")
    investigator_affiliation: str | None = Field(None, alias="investigatorAffiliation")
    old_name_title: str | None = Field(None, alias="oldNameTitle")
    old_organization: str | None = Field(None, alias="oldOrganization")


class CertainAgreement(BaseModel):
    pi_sponsor_employee: bool | None = Field(None, alias="piSponsorEmployee")
    restriction_type: AgreementRestrictionType | None = Field(None, alias="restrictionType")
    restrictive_agreement: bool | None = Field(None, alias="restrictiveAgreement")
    other_details: str | None = Field(None, alias="otherDetails")


class UnpostedEvent(BaseModel):
    type: UnpostedEventType | None = None
    date: date_aliased | None = None
    date_unknown: bool | None = Field(None, alias="dateUnknown")


class Contact(BaseModel):
    name: str | None = None
    role: ContactRole | None = None
    phone: str | None = None
    phone_ext: str | None = Field(None, alias="phoneExt")
    email: str | None = None


class PartialDateStruct(BaseModel):
    date: PartialDate | None = None
    type: DateType | None = None


class Reference(BaseModel):
    pmid: str | None = None
    type: ReferenceType | None = None
    citation: str | None = None
    retractions: list[Retraction] | None = None


class Location(BaseModel):
    facility: str | None = None
    status: RecruitmentStatus | None = None
    city: GeoName | None = None
    state: GeoName | None = None
    zip: str | None = None
    country: str | None = None
    contacts: list[Contact] | None = None
    geo_point: GeoPoint | None = Field(None, alias="geoPoint")


class Sponsor(BaseModel):
    name: str | None = None
    class_: AgencyClass | None = Field(None, alias="class")


class Official(BaseModel):
    name: str | None = None
    affiliation: str | None = None
    role: OfficialRole | None = None


class BrowseLeaf(BaseModel):
    id: str | None = None
    name: str | None = None
    as_found: str | None = Field(None, alias="asFound")
    relevance: BrowseLeafRelevance | None = None


class MaskingBlock(BaseModel):
    masking: DesignMasking | None = None
    masking_description: str | None = Field(None, alias="maskingDescription")
    who_masked: list[WhoMasked] | None = Field(None, alias="whoMasked")


class MeasureAnalysis(BaseModel):
    param_type: str | None = Field(None, alias="paramType")
    param_value: str | None = Field(None, alias="paramValue")
    dispersion_type: AnalysisDispersionType | None = Field(None, alias="dispersionType")
    dispersion_value: str | None = Field(None, alias="dispersionValue")
    statistical_method: str | None = Field(None, alias="statisticalMethod")
    statistical_comment: str | None = Field(None, alias="statisticalComment")
    p_value: str | None = Field(None, alias="pValue")
    p_value_comment: str | None = Field(None, alias="pValueComment")
    ci_num_sides: ConfidenceIntervalNumSides | None = Field(None, alias="ciNumSides")
    ci_pct_value: str | None = Field(None, alias="ciPctValue")
    ci_lower_limit: str | None = Field(None, alias="ciLowerLimit")
    ci_upper_limit: str | None = Field(None, alias="ciUpperLimit")
    ci_lower_limit_comment: str | None = Field(None, alias="ciLowerLimitComment")
    ci_upper_limit_comment: str | None = Field(None, alias="ciUpperLimitComment")
    estimate_comment: str | None = Field(None, alias="estimateComment")
    tested_non_inferiority: bool | None = Field(None, alias="testedNonInferiority")
    non_inferiority_type: NonInferiorityType | None = Field(None, alias="nonInferiorityType")
    non_inferiority_comment: str | None = Field(None, alias="nonInferiorityComment")
    other_analysis_description: str | None = Field(None, alias="otherAnalysisDescription")
    group_description: str | None = Field(None, alias="groupDescription")
    group_ids: list[str] | None = Field(None, alias="groupIds")


class AdverseEvent(BaseModel):
    term: str | None = None
    organ_system: str | None = Field(None, alias="organSystem")
    source_vocabulary: str | None = Field(None, alias="sourceVocabulary")
    assessment_type: EventAssessment | None = Field(None, alias="assessmentType")
    notes: str | None = None
    stats: list[EventStats] | None = None


class Denom(BaseModel):
    units: str | None = None
    counts: list[DenomCount] | None = None


class LargeDoc(BaseModel):
    type_abbrev: str | None = Field(None, alias="typeAbbrev")
    has_protocol: bool | None = Field(None, alias="hasProtocol")
    has_sap: bool | None = Field(None, alias="hasSap")
    has_icf: bool | None = Field(None, alias="hasIcf")
    label: str | None = None
    date: date_aliased | None = None
    upload_date: DateTimeMinutes | None = Field(None, alias="uploadDate")
    filename: str | None = None
    size: int | None = None


class DropWithdraw(BaseModel):
    type: str | None = None
    comment: str | None = None
    reasons: list[FlowStats] | None = None


class MeasureCategory(BaseModel):
    title: str | None = None
    measurements: list[Measurement] | None = None


class FlowMilestone(BaseModel):
    type: str | None = None
    comment: str | None = None
    achievements: list[FlowStats] | None = None


class FieldValuesStats(
    RootModel[EnumStats | StringStats | DateStats | IntegerStats | NumberStats | BooleanStats]
):
    root: EnumStats | StringStats | DateStats | IntegerStats | NumberStats | BooleanStats


class SearchDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    areas: list[SearchArea]
    name: str


class SearchDocumentList(RootModel[list[SearchDocument]]):
    root: list[SearchDocument]


class IdentificationModule(BaseModel):
    nct_id: Nct | None = Field(None, alias="nctId")
    nct_id_aliases: list[Nct] | None = Field(None, alias="nctIdAliases")
    org_study_id_info: OrgStudyIdInfo | None = Field(None, alias="orgStudyIdInfo")
    secondary_id_infos: list[SecondaryIdInfo] | None = Field(None, alias="secondaryIdInfos")
    brief_title: str | None = Field(None, alias="briefTitle")
    official_title: str | None = Field(None, alias="officialTitle")
    acronym: str | None = None
    organization: Organization | None = None


class StatusModule(BaseModel):
    status_verified_date: PartialDate | None = Field(None, alias="statusVerifiedDate")
    overall_status: Status | None = Field(None, alias="overallStatus")
    last_known_status: Status | None = Field(None, alias="lastKnownStatus")
    delayed_posting: bool | None = Field(None, alias="delayedPosting")
    why_stopped: str | None = Field(None, alias="whyStopped")
    expanded_access_info: ExpandedAccessInfo | None = Field(None, alias="expandedAccessInfo")
    start_date_struct: PartialDateStruct | None = Field(None, alias="startDateStruct")
    primary_completion_date_struct: PartialDateStruct | None = Field(
        None, alias="primaryCompletionDateStruct"
    )
    completion_date_struct: PartialDateStruct | None = Field(None, alias="completionDateStruct")
    study_first_submit_date: date_aliased | None = Field(None, alias="studyFirstSubmitDate")
    study_first_submit_qc_date: date_aliased | None = Field(None, alias="studyFirstSubmitQcDate")
    study_first_post_date_struct: DateStruct | None = Field(None, alias="studyFirstPostDateStruct")
    results_waived: bool | None = Field(None, alias="resultsWaived")
    results_first_submit_date: date_aliased | None = Field(None, alias="resultsFirstSubmitDate")
    results_first_submit_qc_date: date_aliased | None = Field(
        None, alias="resultsFirstSubmitQcDate"
    )
    results_first_post_date_struct: DateStruct | None = Field(
        None, alias="resultsFirstPostDateStruct"
    )
    disp_first_submit_date: date_aliased | None = Field(None, alias="dispFirstSubmitDate")
    disp_first_submit_qc_date: date_aliased | None = Field(None, alias="dispFirstSubmitQcDate")
    disp_first_post_date_struct: DateStruct | None = Field(None, alias="dispFirstPostDateStruct")
    last_update_submit_date: date_aliased | None = Field(None, alias="lastUpdateSubmitDate")
    last_update_post_date_struct: DateStruct | None = Field(None, alias="lastUpdatePostDateStruct")


class SponsorCollaboratorsModule(BaseModel):
    responsible_party: ResponsibleParty | None = Field(None, alias="responsibleParty")
    lead_sponsor: Sponsor | None = Field(None, alias="leadSponsor")
    collaborators: list[Sponsor] | None = None


class ArmsInterventionsModule(BaseModel):
    arm_groups: list[ArmGroup] | None = Field(None, alias="armGroups")
    interventions: list[Intervention] | None = None


class ContactsLocationsModule(BaseModel):
    central_contacts: list[Contact] | None = Field(None, alias="centralContacts")
    overall_officials: list[Official] | None = Field(None, alias="overallOfficials")
    locations: list[Location] | None = None


class ReferencesModule(BaseModel):
    references: list[Reference] | None = None
    see_also_links: list[SeeAlsoLink] | None = Field(None, alias="seeAlsoLinks")
    avail_ipds: list[AvailIpd] | None = Field(None, alias="availIpds")


class MoreInfoModule(BaseModel):
    limitations_and_caveats: LimitationsAndCaveats | None = Field(
        None, alias="limitationsAndCaveats"
    )
    certain_agreement: CertainAgreement | None = Field(None, alias="certainAgreement")
    point_of_contact: PointOfContact | None = Field(None, alias="pointOfContact")


class UnpostedAnnotation(BaseModel):
    unposted_responsible_party: str | None = Field(None, alias="unpostedResponsibleParty")
    unposted_events: list[UnpostedEvent] | None = Field(None, alias="unpostedEvents")


class ViolationAnnotation(BaseModel):
    violation_events: list[ViolationEvent] | None = Field(None, alias="violationEvents")


class FirstMcpInfo(BaseModel):
    post_date_struct: DateStruct | None = Field(None, alias="postDateStruct")


class AdverseEventsModule(BaseModel):
    frequency_threshold: str | None = Field(None, alias="frequencyThreshold")
    time_frame: str | None = Field(None, alias="timeFrame")
    description: str | None = None
    all_cause_mortality_comment: str | None = Field(None, alias="allCauseMortalityComment")
    event_groups: list[EventGroup] | None = Field(None, alias="eventGroups")
    serious_events: list[AdverseEvent] | None = Field(None, alias="seriousEvents")
    other_events: list[AdverseEvent] | None = Field(None, alias="otherEvents")


class DesignInfo(BaseModel):
    allocation: DesignAllocation | None = None
    intervention_model: InterventionalAssignment | None = Field(None, alias="interventionModel")
    intervention_model_description: str | None = Field(None, alias="interventionModelDescription")
    primary_purpose: PrimaryPurpose | None = Field(None, alias="primaryPurpose")
    observational_model: ObservationalModel | None = Field(None, alias="observationalModel")
    time_perspective: DesignTimePerspective | None = Field(None, alias="timePerspective")
    masking_info: MaskingBlock | None = Field(None, alias="maskingInfo")


class LargeDocumentModule(BaseModel):
    no_sap: bool | None = Field(None, alias="noSap")
    large_docs: list[LargeDoc] | None = Field(None, alias="largeDocs")


class BrowseModule(BaseModel):
    meshes: list[Mesh] | None = None
    ancestors: list[Mesh] | None = None
    browse_leaves: list[BrowseLeaf] | None = Field(None, alias="browseLeaves")
    browse_branches: list[BrowseBranch] | None = Field(None, alias="browseBranches")


class FlowPeriod(BaseModel):
    title: str | None = None
    milestones: list[FlowMilestone] | None = None
    drop_withdraws: list[DropWithdraw] | None = Field(None, alias="dropWithdraws")


class MeasureClass(BaseModel):
    title: str | None = None
    denoms: list[Denom] | None = None
    categories: list[MeasureCategory] | None = None


class BaselineMeasure(BaseModel):
    title: str | None = None
    description: str | None = None
    population_description: str | None = Field(None, alias="populationDescription")
    param_type: MeasureParam | None = Field(None, alias="paramType")
    dispersion_type: MeasureDispersionType | None = Field(None, alias="dispersionType")
    unit_of_measure: str | None = Field(None, alias="unitOfMeasure")
    calculate_pct: bool | None = Field(None, alias="calculatePct")
    denom_units_selected: str | None = Field(None, alias="denomUnitsSelected")
    denoms: list[Denom] | None = None
    classes: list[MeasureClass] | None = None


class FieldValuesStatsList(RootModel[list[FieldValuesStats]]):
    root: list[FieldValuesStats]


class DocumentSection(BaseModel):
    large_document_module: LargeDocumentModule | None = Field(None, alias="largeDocumentModule")


class DesignModule(BaseModel):
    study_type: StudyType | None = Field(None, alias="studyType")
    n_ptrs_to_this_exp_acc_nct_id: int | None = Field(None, alias="nPtrsToThisExpAccNctId")
    expanded_access_types: ExpandedAccessTypes | None = Field(None, alias="expandedAccessTypes")
    patient_registry: bool | None = Field(None, alias="patientRegistry")
    target_duration: (
        constr(
            pattern=r"^\d+ (Year|Years|Month|Months|Week|Weeks|Day|Days|Hour|Hours|Minute|Minutes)$"
        )
        | None
    ) = Field(None, alias="targetDuration")
    phases: list[Phase] | None = None
    design_info: DesignInfo | None = Field(None, alias="designInfo")
    bio_spec: BioSpec | None = Field(None, alias="bioSpec")
    enrollment_info: EnrollmentInfo | None = Field(None, alias="enrollmentInfo")


class AnnotationModule(BaseModel):
    unposted_annotation: UnpostedAnnotation | None = Field(None, alias="unpostedAnnotation")
    violation_annotation: ViolationAnnotation | None = Field(None, alias="violationAnnotation")


class SubmissionTracking(BaseModel):
    estimated_results_first_submit_date: date_aliased | None = Field(
        None, alias="estimatedResultsFirstSubmitDate"
    )
    first_mcp_info: FirstMcpInfo | None = Field(None, alias="firstMcpInfo")
    submission_infos: list[SubmissionInfo] | None = Field(None, alias="submissionInfos")


class OutcomeMeasure(BaseModel):
    type: OutcomeMeasureType | None = None
    title: str | None = None
    description: str | None = None
    population_description: str | None = Field(None, alias="populationDescription")
    reporting_status: ReportingStatus | None = Field(None, alias="reportingStatus")
    anticipated_posting_date: PartialDate | None = Field(None, alias="anticipatedPostingDate")
    param_type: MeasureParam | None = Field(None, alias="paramType")
    dispersion_type: str | None = Field(None, alias="dispersionType")
    unit_of_measure: str | None = Field(None, alias="unitOfMeasure")
    calculate_pct: bool | None = Field(None, alias="calculatePct")
    time_frame: str | None = Field(None, alias="timeFrame")
    type_units_analyzed: str | None = Field(None, alias="typeUnitsAnalyzed")
    denom_units_selected: str | None = Field(None, alias="denomUnitsSelected")
    groups: list[MeasureGroup] | None = None
    denoms: list[Denom] | None = None
    classes: list[MeasureClass] | None = None
    analyses: list[MeasureAnalysis] | None = None


class BaselineCharacteristicsModule(BaseModel):
    population_description: str | None = Field(None, alias="populationDescription")
    type_units_analyzed: str | None = Field(None, alias="typeUnitsAnalyzed")
    groups: list[MeasureGroup] | None = None
    denoms: list[Denom] | None = None
    measures: list[BaselineMeasure] | None = None


class ParticipantFlowModule(BaseModel):
    pre_assignment_details: str | None = Field(None, alias="preAssignmentDetails")
    recruitment_details: str | None = Field(None, alias="recruitmentDetails")
    type_units_analyzed: str | None = Field(None, alias="typeUnitsAnalyzed")
    groups: list[FlowGroup] | None = None
    periods: list[FlowPeriod] | None = None


class ProtocolSection(BaseModel):
    identification_module: IdentificationModule | None = Field(None, alias="identificationModule")
    status_module: StatusModule | None = Field(None, alias="statusModule")
    sponsor_collaborators_module: SponsorCollaboratorsModule | None = Field(
        None, alias="sponsorCollaboratorsModule"
    )
    oversight_module: OversightModule | None = Field(None, alias="oversightModule")
    description_module: DescriptionModule | None = Field(None, alias="descriptionModule")
    conditions_module: ConditionsModule | None = Field(None, alias="conditionsModule")
    design_module: DesignModule | None = Field(None, alias="designModule")
    arms_interventions_module: ArmsInterventionsModule | None = Field(
        None, alias="armsInterventionsModule"
    )
    outcomes_module: OutcomesModule | None = Field(None, alias="outcomesModule")
    eligibility_module: EligibilityModule | None = Field(None, alias="eligibilityModule")
    contacts_locations_module: ContactsLocationsModule | None = Field(
        None, alias="contactsLocationsModule"
    )
    references_module: ReferencesModule | None = Field(None, alias="referencesModule")
    ipd_sharing_statement_module: IpdSharingStatementModule | None = Field(
        None, alias="ipdSharingStatementModule"
    )


class AnnotationSection(BaseModel):
    annotation_module: AnnotationModule | None = Field(None, alias="annotationModule")


class OutcomeMeasuresModule(BaseModel):
    outcome_measures: list[OutcomeMeasure] | None = Field(None, alias="outcomeMeasures")


class MiscInfoModule(BaseModel):
    version_holder: date_aliased | None = Field(None, alias="versionHolder")
    removed_countries: list[str] | None = Field(None, alias="removedCountries")
    submission_tracking: SubmissionTracking | None = Field(None, alias="submissionTracking")


class ResultsSection(BaseModel):
    participant_flow_module: ParticipantFlowModule | None = Field(
        None, alias="participantFlowModule"
    )
    baseline_characteristics_module: BaselineCharacteristicsModule | None = Field(
        None, alias="baselineCharacteristicsModule"
    )
    outcome_measures_module: OutcomeMeasuresModule | None = Field(
        None, alias="outcomeMeasuresModule"
    )
    adverse_events_module: AdverseEventsModule | None = Field(None, alias="adverseEventsModule")
    more_info_module: MoreInfoModule | None = Field(None, alias="moreInfoModule")


class DerivedSection(BaseModel):
    misc_info_module: MiscInfoModule | None = Field(None, alias="miscInfoModule")
    condition_browse_module: BrowseModule | None = Field(None, alias="conditionBrowseModule")
    intervention_browse_module: BrowseModule | None = Field(None, alias="interventionBrowseModule")


class Study(BaseModel):
    protocol_section: ProtocolSection | None = Field(None, alias="protocolSection")
    results_section: ResultsSection | None = Field(None, alias="resultsSection")
    annotation_section: AnnotationSection | None = Field(None, alias="annotationSection")
    document_section: DocumentSection | None = Field(None, alias="documentSection")
    derived_section: DerivedSection | None = Field(None, alias="derivedSection")
    has_results: bool | None = Field(None, alias="hasResults")


class StudyList(RootModel[list[Study]]):
    """
    `study` field values of type `markup` are in markdown format.

    """

    root: list[Study] = Field(
        ...,
        description="`study` field values of type `markup` are in markdown format.\n",
        title="Array of studies",
    )


class PagedStudies(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    next_page_token: str | None = Field(None, alias="nextPageToken")
    studies: StudyList
    total_count: int | None = Field(None, alias="totalCount")


FieldNode.model_rebuild()
